### ISSUE TITLE
enabling UART2 breaks esp32-proxy

### ISSUE THREAD

**Issue by hdumcke** [mangdangroboticsclub/mini_pupper_2_bsp#47]
### Reproduction steps

https://github.com/mangdangroboticsclub/mini_pupper_2_bsp/pull/43 breaks esp32-proxy

### Actual results

servos do not move

### Expected results

servos will move

### Version

Mini Pupper 2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mangdangroboticsclub** [comment]
I tested the bsp features based on readme and have not found any issues yet.
Let's double-confirm later after we have the new board.

**Comment by hdumcke** [comment]
actually it turns out that this is related to the order how services are started and will be fixed. Please close this issue

**Comment by mangdangroboticsclub** [comment]
OK, thanks
